# Site Info
title: 'Software Shit Shark notes'
tagline: '@DimYurich on Java / JVM, IR, ML, and maintenance of legacy systems'
#tagline: 'All opinions expressed here are of my own, not of my employer(s)'
description: 'Notes on Search and legacy systems. How to maintain them, make them better, pull them out of misery and oblivion'
url: http://dimyurich.github.io
logo: public/favicon.ico
# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: <!--more-->
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Dmitry Terentyev
  description: A software developer focusing in search and legacy systems. All opinions expressed here are of my own, not of my employer(s)
  gravatar: 73d796a3bf5de675afa4e7762e5bf450 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/dterentyev
    github:    https://github.com/dimyurich
    twitter:   https://twitter.com/dimyurich
    instagram: https://www.instagram.com/dimyurich

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Tags:
    - '/tags/'
  About:
    - '/about/'
  Github Project:
    - 'https://github.com/DimYurich/dimyurich.github.io'

# Where are tags and categories displayed
tag_page: '/tags/'

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-102902604-1' # leave blank if you don't want google analytics
disqus_short_name: 'dimyurich' # leave blank if you don't want disqus
